language: php
php:
  - 5.6
matrix:
  allow_failures:
    - php: 5.6
services: mysql
before_script: 
- cp .env.travis .env
- mysql -e 'create database ocoder_education;'
- mysql ocoder_education < travis/ocoder_education.sql
- composer self-update
- composer install --no-interaction
script:   
- /vendor/bin/codecept run
deploy:
  provider: heroku
  api_key: "e829183d-1e65-40f3-9a86-611d6677e8dd"	